<?php
$currencies = array(
    array(
        'symbol'=> '$',
        'name'=> __('US Dollar', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> '$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'USD',
        'name_plural'=> __('US dollars', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'CA$',
        'name'=> __('Canadian Dollar', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> '$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'CAD',
        'name_plural'=> __('Canadian dollars', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> '€',
        'name'=> __('Euro', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> '€',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'EUR',
        'name_plural'=> __('euros', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'AED',
        'name'=> __('United Arab Emirates Dirham', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'د.إ.‏',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'AED',
        'name_plural'=> __('UAE dirhams', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'Af',
        'name'=> __('Afghan Afghani', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> '؋',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'AFN',
        'name_plural'=> __('Afghan Afghanis', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'ALL',
        'name'=> __('Albanian Lek', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'Lek',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'ALL',
        'name_plural'=> __('Albanian lekë', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'AMD',
        'name'=> __('Armenian Dram', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'դր.',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'AMD',
        'name_plural'=> __('Armenian drams', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'AR$',
        'name'=> __('Argentine Peso', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> '$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'ARS',
        'name_plural'=> __('Argentine pesos', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'AU$',
        'name'=> __('Australian Dollar', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> '$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'AUD',
        'name_plural'=> __('Australian dollars', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'man.',
        'name'=> __('Azerbaijani Manat', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'ман.',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'AZN',
        'name_plural'=> __('Azerbaijani manats', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'KM',
        'name'=> __('Bosnia-Herzegovina Convertible Mark', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'KM',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'BAM',
        'name_plural'=> __('Bosnia-Herzegovina convertible marks', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'Tk',
        'name'=> __('Bangladeshi Taka', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> '৳',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'BDT',
        'name_plural'=> __('Bangladeshi takas', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'BGN',
        'name'=> __('Bulgarian Lev', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'лв.',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'BGN',
        'name_plural'=> __('Bulgarian leva', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'BD',
        'name'=> __('Bahraini Dinar', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'د.ب.‏',
        'decimal_digits'=> 3,
        'rounding'=> 0,
        'code'=> 'BHD',
        'name_plural'=> __('Bahraini dinars', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'FBu',
        'name'=> __('Burundian Franc', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'FBu',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'BIF',
        'name_plural'=> __('Burundian francs', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'BN$',
        'name'=> __('Brunei Dollar', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> '$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'BND',
        'name_plural'=> __('Brunei dollars', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'Bs',
        'name'=> __('Bolivian Boliviano', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'Bs',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'BOB',
        'name_plural'=> __('Bolivian bolivianos', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'R$',
        'name'=> __('Brazilian Real', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'R$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'BRL',
        'name_plural'=> __('Brazilian reals', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'BWP',
        'name'=> __('Botswanan Pula', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'P',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'BWP',
        'name_plural'=> __('Botswanan pulas', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'BYR',
        'name'=> __('Belarusian Ruble', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'BYR',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'BYR',
        'name_plural'=> __('Belarusian rubles', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'BZ$',
        'name'=> __('Belize Dollar', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> '$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'BZD',
        'name_plural'=> __('Belize dollars', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'CDF',
        'name'=> __('Congolese Franc', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'FrCD',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'CDF',
        'name_plural'=> __('Congolese francs', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'CHF',
        'name'=> __('Swiss Franc', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'CHF',
        'decimal_digits'=> 2,
        'rounding'=> 0.05,
        'code'=> 'CHF',
        'name_plural'=> __('Swiss francs', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'CL$',
        'name'=> __('Chilean Peso', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> '$',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'CLP',
        'name_plural'=> __('Chilean pesos', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'CN¥',
        'name'=> __('Chinese Yuan', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'CN¥',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'CNY',
        'name_plural'=> __('Chinese yuan', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'CO$',
        'name'=> __('Colombian Peso', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> '$',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'COP',
        'name_plural'=> __('Colombian pesos', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> '₡',
        'name'=> __('Costa Rican Colón', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> '₡',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'CRC',
        'name_plural'=> __('Costa Rican colóns', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'CV$',
        'name'=> __('Cape Verdean Escudo', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'CV$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'CVE',
        'name_plural'=> __('Cape Verdean escudos', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'Kč',
        'name'=> __('Czech Republic Koruna', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'Kč',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'CZK',
        'name_plural'=> __('Czech Republic korunas', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'Fdj',
        'name'=> __('Djiboutian Franc', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'Fdj',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'DJF',
        'name_plural'=> __('Djiboutian francs', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'Dkr',
        'name'=> __('Danish Krone', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'kr',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'DKK',
        'name_plural'=> __('Danish kroner', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'RD$',
        'name'=> __('Dominican Peso', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'RD$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'DOP',
        'name_plural'=> __('Dominican pesos', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'DA',
        'name'=> __('Algerian Dinar', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'د.ج.‏',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'DZD',
        'name_plural'=> __('Algerian dinars', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'Ekr',
        'name'=> __('Estonian Kroon', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'kr',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'EEK',
        'name_plural'=> __('Estonian kroons', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'EGP',
        'name'=> __('Egyptian Pound', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'ج.م.‏',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'EGP',
        'name_plural'=> __('Egyptian pounds', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'Nfk',
        'name'=> __('Eritrean Nakfa', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'Nfk',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'ERN',
        'name_plural'=> __('Eritrean nakfas', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'Br',
        'name'=> __('Ethiopian Birr', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'Br',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'ETB',
        'name_plural'=> __('Ethiopian birrs', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> '£',
        'name'=> __('British Pound Sterling', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> '£',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'GBP',
        'name_plural'=> __('British pounds sterling', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'GEL',
        'name'=> __('Georgian Lari', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'GEL',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'GEL',
        'name_plural'=> __('Georgian laris', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'GH₵',
        'name'=> __('Ghanaian Cedi', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'GH₵',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'GHS',
        'name_plural'=> __('Ghanaian cedis', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'FG',
        'name'=> __('Guinean Franc', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'FG',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'GNF',
        'name_plural'=> __('Guinean francs', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'GTQ',
        'name'=> __('Guatemalan Quetzal', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'Q',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'GTQ',
        'name_plural'=> __('Guatemalan quetzals', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'HK$',
        'name'=> __('Hong Kong Dollar', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> '$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'HKD',
        'name_plural'=> __('Hong Kong dollars', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'HNL',
        'name'=> __('Honduran Lempira', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'L',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'HNL',
        'name_plural'=> __('Honduran lempiras', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'kn',
        'name'=> __('Croatian Kuna', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'kn',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'HRK',
        'name_plural'=> __('Croatian kunas', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'Ft',
        'name'=> __('Hungarian Forint', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'Ft',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'HUF',
        'name_plural'=> __('Hungarian forints', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'Rp',
        'name'=> __('Indonesian Rupiah', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'Rp',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'IDR',
        'name_plural'=> __('Indonesian rupiahs', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> '₪',
        'name'=> __('Israeli New Sheqel', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> '₪',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'ILS',
        'name_plural'=> __('Israeli new sheqels', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'Rs',
        'name'=> __('Indian Rupee', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'টকা',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'INR',
        'name_plural'=> __('Indian rupees', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'IQD',
        'name'=> __('Iraqi Dinar', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'د.ع.‏',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'IQD',
        'name_plural'=> __('Iraqi dinars', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'IRR',
        'name'=> __('Iranian Rial', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> '﷼',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'IRR',
        'name_plural'=> __('Iranian rials', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'Ikr',
        'name'=> __('Icelandic Króna', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'kr',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'ISK',
        'name_plural'=> __('Icelandic krónur', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'J$',
        'name'=> __('Jamaican Dollar', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> '$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'JMD',
        'name_plural'=> __('Jamaican dollars', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'JD',
        'name'=> __('Jordanian Dinar', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'د.أ.‏',
        'decimal_digits'=> 3,
        'rounding'=> 0,
        'code'=> 'JOD',
        'name_plural'=> __('Jordanian dinars', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> '¥',
        'name'=> __('Japanese Yen', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> '￥',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'JPY',
        'name_plural'=> __('Japanese yen', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'Ksh',
        'name'=> __('Kenyan Shilling', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'Ksh',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'KES',
        'name_plural'=> __('Kenyan shillings', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'KHR',
        'name'=> __('Cambodian Riel', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> '៛',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'KHR',
        'name_plural'=> __('Cambodian riels', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'CF',
        'name'=> __('Comorian Franc', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'FC',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'KMF',
        'name_plural'=> __('Comorian francs', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> '₩',
        'name'=> __('South Korean Won', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> '₩',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'KRW',
        'name_plural'=> __('South Korean won', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'KD',
        'name'=> __('Kuwaiti Dinar', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'د.ك.‏',
        'decimal_digits'=> 3,
        'rounding'=> 0,
        'code'=> 'KWD',
        'name_plural'=> __('Kuwaiti dinars', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'KZT',
        'name'=> __('Kazakhstani Tenge', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'тңг.',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'KZT',
        'name_plural'=> __('Kazakhstani tenges', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'LB£',
        'name'=> __('Lebanese Pound', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'ل.ل.‏',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'LBP',
        'name_plural'=> __('Lebanese pounds', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'SLRs',
        'name'=> __('Sri Lankan Rupee', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'SL Re',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'LKR',
        'name_plural'=> __('Sri Lankan rupees', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'Lt',
        'name'=> __('Lithuanian Litas', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'Lt',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'LTL',
        'name_plural'=> __('Lithuanian litai', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'Ls',
        'name'=> __('Latvian Lats', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'Ls',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'LVL',
        'name_plural'=> __('Latvian lati', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'LD',
        'name'=> __('Libyan Dinar', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'د.ل.‏',
        'decimal_digits'=> 3,
        'rounding'=> 0,
        'code'=> 'LYD',
        'name_plural'=> __('Libyan dinars', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'MAD',
        'name'=> __('Moroccan Dirham', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'د.م.‏',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'MAD',
        'name_plural'=> __('Moroccan dirhams', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'MDL',
        'name'=> __('Moldovan Leu', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'MDL',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'MDL',
        'name_plural'=> __('Moldovan lei', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'MGA',
        'name'=> __('Malagasy Ariary', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'MGA',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'MGA',
        'name_plural'=> __('Malagasy Ariaries', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'MKD',
        'name'=> __('Macedonian Denar', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'MKD',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'MKD',
        'name_plural'=> __('Macedonian denari', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'MMK',
        'name'=> __('Myanma Kyat', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'K',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'MMK',
        'name_plural'=> __('Myanma kyats', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'MOP$',
        'name'=> __('Macanese Pataca', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'MOP$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'MOP',
        'name_plural'=> __('Macanese patacas', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'MURs',
        'name'=> __('Mauritian Rupee', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'MURs',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'MUR',
        'name_plural'=> __('Mauritian rupees', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'MX$',
        'name'=> __('Mexican Peso', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> '$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'MXN',
        'name_plural'=> __('Mexican pesos', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'RM',
        'name'=> __('Malaysian Ringgit', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'RM',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'MYR',
        'name_plural'=> __('Malaysian ringgits', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'MTn',
        'name'=> __('Mozambican Metical', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'MTn',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'MZN',
        'name_plural'=> __('Mozambican meticals', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'N$',
        'name'=> __('Namibian Dollar', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'N$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'NAD',
        'name_plural'=> __('Namibian dollars', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> '₦',
        'name'=> __('Nigerian Naira', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> '₦',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'NGN',
        'name_plural'=> __('Nigerian nairas', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'C$',
        'name'=> __('Nicaraguan Córdoba', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'C$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'NIO',
        'name_plural'=> __('Nicaraguan córdobas', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'Nkr',
        'name'=> __('Norwegian Krone', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'kr',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'NOK',
        'name_plural'=> __('Norwegian kroner', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'NPRs',
        'name'=> __('Nepalese Rupee', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'नेरू',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'NPR',
        'name_plural'=> __('Nepalese rupees', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'NZ$',
        'name'=> __('New Zealand Dollar', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> '$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'NZD',
        'name_plural'=> __('New Zealand dollars', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'OMR',
        'name'=> __('Omani Rial', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'ر.ع.‏',
        'decimal_digits'=> 3,
        'rounding'=> 0,
        'code'=> 'OMR',
        'name_plural'=> __('Omani rials', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'B/.',
        'name'=> __('Panamanian Balboa', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'B/.',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'PAB',
        'name_plural'=> __('Panamanian balboas', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'S/.',
        'name'=> __('Peruvian Nuevo Sol', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'S/.',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'PEN',
        'name_plural'=> __('Peruvian nuevos soles', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> '₱',
        'name'=> __('Philippine Peso', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> '₱',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'PHP',
        'name_plural'=> __('Philippine pesos', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'PKRs',
        'name'=> __('Pakistani Rupee', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> '₨',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'PKR',
        'name_plural'=> __('Pakistani rupees', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'zł',
        'name'=> __('Polish Zloty', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'zł',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'PLN',
        'name_plural'=> __('Polish zlotys', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> '₲',
        'name'=> __('Paraguayan Guarani', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> '₲',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'PYG',
        'name_plural'=> __('Paraguayan guaranis', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'QR',
        'name'=> __('Qatari Rial', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'ر.ق.‏',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'QAR',
        'name_plural'=> __('Qatari rials', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'RON',
        'name'=> __('Romanian Leu', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'RON',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'RON',
        'name_plural'=> __('Romanian lei', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'din.',
        'name'=> __('Serbian Dinar', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'дин.',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'RSD',
        'name_plural'=> __('Serbian dinars', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'RUB',
        'name'=> __('Russian Ruble', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'руб.',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'RUB',
        'name_plural'=> __('Russian rubles', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'RWF',
        'name'=> __('Rwandan Franc', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'FR',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'RWF',
        'name_plural'=> __('Rwandan francs', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'SR',
        'name'=> __('Saudi Riyal', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'ر.س.‏',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'SAR',
        'name_plural'=> __('Saudi riyals', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'SDG',
        'name'=> __('Sudanese Pound', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'SDG',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'SDG',
        'name_plural'=> __('Sudanese pounds', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'Skr',
        'name'=> __('Swedish Krona', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'kr',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'SEK',
        'name_plural'=> __('Swedish kronor', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'S$',
        'name'=> __('Singapore Dollar', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> '$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'SGD',
        'name_plural'=> __('Singapore dollars', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'Ssh',
        'name'=> __('Somali Shilling', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'Ssh',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'SOS',
        'name_plural'=> __('Somali shillings', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'SY£',
        'name'=> __('Syrian Pound', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'ل.س.‏',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'SYP',
        'name_plural'=> __('Syrian pounds', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> '฿',
        'name'=> __('Thai Baht', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> '฿',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'THB',
        'name_plural'=> __('Thai baht', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'DT',
        'name'=> __('Tunisian Dinar', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'د.ت.‏',
        'decimal_digits'=> 3,
        'rounding'=> 0,
        'code'=> 'TND',
        'name_plural'=> __('Tunisian dinars', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'T$',
        'name'=> __('Tongan Paʻanga', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'T$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'TOP',
        'name_plural'=> __('Tongan paʻanga', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'TL',
        'name'=> __('Turkish Lira', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'TL',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'TRY',
        'name_plural'=> __('Turkish Lira', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'TT$',
        'name'=> __('Trinidad and Tobago Dollar', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> '$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'TTD',
        'name_plural'=> __('Trinidad and Tobago dollars', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'NT$',
        'name'=> __('New Taiwan Dollar', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'NT$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'TWD',
        'name_plural'=> __('New Taiwan dollars', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'TSh',
        'name'=> __('Tanzanian Shilling', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'TSh',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'TZS',
        'name_plural'=> __('Tanzanian shillings', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> '₴',
        'name'=> __('Ukrainian Hryvnia', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> '₴',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'UAH',
        'name_plural'=> __('Ukrainian hryvnias', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'USh',
        'name'=> __('Ugandan Shilling', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'USh',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'UGX',
        'name_plural'=> __('Ugandan shillings', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> '$U',
        'name'=> __('Uruguayan Peso', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> '$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'UYU',
        'name_plural'=> __('Uruguayan pesos', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'UZS',
        'name'=> __('Uzbekistan Som', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'UZS',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'UZS',
        'name_plural'=> __('Uzbekistan som', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'Bs.F.',
        'name'=> __('Venezuelan Bolívar', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'Bs.F.',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'VEF',
        'name_plural'=> __('Venezuelan bolívars', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> '₫',
        'name'=> __('Vietnamese Dong', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> '₫',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'VND',
        'name_plural'=> __('Vietnamese dong', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'FCFA',
        'name'=> __('CFA Franc BEAC', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'FCFA',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'XAF',
        'name_plural'=> __('CFA francs BEAC', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'CFA',
        'name'=> __('CFA Franc BCEAO', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'CFA',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'XOF',
        'name_plural'=> __('CFA francs BCEAO', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'YR',
        'name'=> __('Yemeni Rial', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'ر.ي.‏',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'YER',
        'name_plural'=> __('Yemeni rials', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'R',
        'name'=> __('South African Rand', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'R',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'ZAR',
        'name_plural'=> __('South African rand', FAKTURO_TEXT_DOMAIN ),
    ),
    array(
        'symbol'=> 'ZK',
        'name'=> __('Zambian Kwacha', FAKTURO_TEXT_DOMAIN ),
        'symbol_native'=> 'ZK',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'ZMK',
        'name_plural'=> __('Zambian kwachas', FAKTURO_TEXT_DOMAIN ),
    )
);
?>