<?php
$currencies = array(
    array(
        'symbol'=> '$',
        'name'=> __('US Dollar', 'fakturo' ),
        'symbol_native'=> '$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'USD',
        'name_plural'=> __('US dollars', 'fakturo' ),
    ),
    array(
        'symbol'=> 'CA$',
        'name'=> __('Canadian Dollar', 'fakturo' ),
        'symbol_native'=> '$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'CAD',
        'name_plural'=> __('Canadian dollars', 'fakturo' ),
    ),
    array(
        'symbol'=> '€',
        'name'=> __('Euro', 'fakturo' ),
        'symbol_native'=> '€',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'EUR',
        'name_plural'=> __('euros', 'fakturo' ),
    ),
    array(
        'symbol'=> 'AED',
        'name'=> __('United Arab Emirates Dirham', 'fakturo' ),
        'symbol_native'=> 'د.إ.‏',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'AED',
        'name_plural'=> __('UAE dirhams', 'fakturo' ),
    ),
    array(
        'symbol'=> 'Af',
        'name'=> __('Afghan Afghani', 'fakturo' ),
        'symbol_native'=> '؋',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'AFN',
        'name_plural'=> __('Afghan Afghanis', 'fakturo' ),
    ),
    array(
        'symbol'=> 'ALL',
        'name'=> __('Albanian Lek', 'fakturo' ),
        'symbol_native'=> 'Lek',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'ALL',
        'name_plural'=> __('Albanian lekë', 'fakturo' ),
    ),
    array(
        'symbol'=> 'AMD',
        'name'=> __('Armenian Dram', 'fakturo' ),
        'symbol_native'=> 'դր.',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'AMD',
        'name_plural'=> __('Armenian drams', 'fakturo' ),
    ),
    array(
        'symbol'=> 'AR$',
        'name'=> __('Argentine Peso', 'fakturo' ),
        'symbol_native'=> '$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'ARS',
        'name_plural'=> __('Argentine pesos', 'fakturo' ),
    ),
    array(
        'symbol'=> 'AU$',
        'name'=> __('Australian Dollar', 'fakturo' ),
        'symbol_native'=> '$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'AUD',
        'name_plural'=> __('Australian dollars', 'fakturo' ),
    ),
    array(
        'symbol'=> 'man.',
        'name'=> __('Azerbaijani Manat', 'fakturo' ),
        'symbol_native'=> 'ман.',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'AZN',
        'name_plural'=> __('Azerbaijani manats', 'fakturo' ),
    ),
    array(
        'symbol'=> 'KM',
        'name'=> __('Bosnia-Herzegovina Convertible Mark', 'fakturo' ),
        'symbol_native'=> 'KM',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'BAM',
        'name_plural'=> __('Bosnia-Herzegovina convertible marks', 'fakturo' ),
    ),
    array(
        'symbol'=> 'Tk',
        'name'=> __('Bangladeshi Taka', 'fakturo' ),
        'symbol_native'=> '৳',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'BDT',
        'name_plural'=> __('Bangladeshi takas', 'fakturo' ),
    ),
    array(
        'symbol'=> 'BGN',
        'name'=> __('Bulgarian Lev', 'fakturo' ),
        'symbol_native'=> 'лв.',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'BGN',
        'name_plural'=> __('Bulgarian leva', 'fakturo' ),
    ),
    array(
        'symbol'=> 'BD',
        'name'=> __('Bahraini Dinar', 'fakturo' ),
        'symbol_native'=> 'د.ب.‏',
        'decimal_digits'=> 3,
        'rounding'=> 0,
        'code'=> 'BHD',
        'name_plural'=> __('Bahraini dinars', 'fakturo' ),
    ),
    array(
        'symbol'=> 'FBu',
        'name'=> __('Burundian Franc', 'fakturo' ),
        'symbol_native'=> 'FBu',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'BIF',
        'name_plural'=> __('Burundian francs', 'fakturo' ),
    ),
    array(
        'symbol'=> 'BN$',
        'name'=> __('Brunei Dollar', 'fakturo' ),
        'symbol_native'=> '$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'BND',
        'name_plural'=> __('Brunei dollars', 'fakturo' ),
    ),
    array(
        'symbol'=> 'Bs',
        'name'=> __('Bolivian Boliviano', 'fakturo' ),
        'symbol_native'=> 'Bs',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'BOB',
        'name_plural'=> __('Bolivian bolivianos', 'fakturo' ),
    ),
    array(
        'symbol'=> 'R$',
        'name'=> __('Brazilian Real', 'fakturo' ),
        'symbol_native'=> 'R$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'BRL',
        'name_plural'=> __('Brazilian reals', 'fakturo' ),
    ),
    array(
        'symbol'=> 'BWP',
        'name'=> __('Botswanan Pula', 'fakturo' ),
        'symbol_native'=> 'P',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'BWP',
        'name_plural'=> __('Botswanan pulas', 'fakturo' ),
    ),
    array(
        'symbol'=> 'BYR',
        'name'=> __('Belarusian Ruble', 'fakturo' ),
        'symbol_native'=> 'BYR',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'BYR',
        'name_plural'=> __('Belarusian rubles', 'fakturo' ),
    ),
    array(
        'symbol'=> 'BZ$',
        'name'=> __('Belize Dollar', 'fakturo' ),
        'symbol_native'=> '$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'BZD',
        'name_plural'=> __('Belize dollars', 'fakturo' ),
    ),
    array(
        'symbol'=> 'CDF',
        'name'=> __('Congolese Franc', 'fakturo' ),
        'symbol_native'=> 'FrCD',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'CDF',
        'name_plural'=> __('Congolese francs', 'fakturo' ),
    ),
    array(
        'symbol'=> 'CHF',
        'name'=> __('Swiss Franc', 'fakturo' ),
        'symbol_native'=> 'CHF',
        'decimal_digits'=> 2,
        'rounding'=> 0.05,
        'code'=> 'CHF',
        'name_plural'=> __('Swiss francs', 'fakturo' ),
    ),
    array(
        'symbol'=> 'CL$',
        'name'=> __('Chilean Peso', 'fakturo' ),
        'symbol_native'=> '$',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'CLP',
        'name_plural'=> __('Chilean pesos', 'fakturo' ),
    ),
    array(
        'symbol'=> 'CN¥',
        'name'=> __('Chinese Yuan', 'fakturo' ),
        'symbol_native'=> 'CN¥',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'CNY',
        'name_plural'=> __('Chinese yuan', 'fakturo' ),
    ),
    array(
        'symbol'=> 'CO$',
        'name'=> __('Colombian Peso', 'fakturo' ),
        'symbol_native'=> '$',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'COP',
        'name_plural'=> __('Colombian pesos', 'fakturo' ),
    ),
    array(
        'symbol'=> '₡',
        'name'=> __('Costa Rican Colón', 'fakturo' ),
        'symbol_native'=> '₡',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'CRC',
        'name_plural'=> __('Costa Rican colóns', 'fakturo' ),
    ),
    array(
        'symbol'=> 'CV$',
        'name'=> __('Cape Verdean Escudo', 'fakturo' ),
        'symbol_native'=> 'CV$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'CVE',
        'name_plural'=> __('Cape Verdean escudos', 'fakturo' ),
    ),
    array(
        'symbol'=> 'Kč',
        'name'=> __('Czech Republic Koruna', 'fakturo' ),
        'symbol_native'=> 'Kč',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'CZK',
        'name_plural'=> __('Czech Republic korunas', 'fakturo' ),
    ),
    array(
        'symbol'=> 'Fdj',
        'name'=> __('Djiboutian Franc', 'fakturo' ),
        'symbol_native'=> 'Fdj',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'DJF',
        'name_plural'=> __('Djiboutian francs', 'fakturo' ),
    ),
    array(
        'symbol'=> 'Dkr',
        'name'=> __('Danish Krone', 'fakturo' ),
        'symbol_native'=> 'kr',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'DKK',
        'name_plural'=> __('Danish kroner', 'fakturo' ),
    ),
    array(
        'symbol'=> 'RD$',
        'name'=> __('Dominican Peso', 'fakturo' ),
        'symbol_native'=> 'RD$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'DOP',
        'name_plural'=> __('Dominican pesos', 'fakturo' ),
    ),
    array(
        'symbol'=> 'DA',
        'name'=> __('Algerian Dinar', 'fakturo' ),
        'symbol_native'=> 'د.ج.‏',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'DZD',
        'name_plural'=> __('Algerian dinars', 'fakturo' ),
    ),
    array(
        'symbol'=> 'Ekr',
        'name'=> __('Estonian Kroon', 'fakturo' ),
        'symbol_native'=> 'kr',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'EEK',
        'name_plural'=> __('Estonian kroons', 'fakturo' ),
    ),
    array(
        'symbol'=> 'EGP',
        'name'=> __('Egyptian Pound', 'fakturo' ),
        'symbol_native'=> 'ج.م.‏',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'EGP',
        'name_plural'=> __('Egyptian pounds', 'fakturo' ),
    ),
    array(
        'symbol'=> 'Nfk',
        'name'=> __('Eritrean Nakfa', 'fakturo' ),
        'symbol_native'=> 'Nfk',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'ERN',
        'name_plural'=> __('Eritrean nakfas', 'fakturo' ),
    ),
    array(
        'symbol'=> 'Br',
        'name'=> __('Ethiopian Birr', 'fakturo' ),
        'symbol_native'=> 'Br',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'ETB',
        'name_plural'=> __('Ethiopian birrs', 'fakturo' ),
    ),
    array(
        'symbol'=> '£',
        'name'=> __('British Pound Sterling', 'fakturo' ),
        'symbol_native'=> '£',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'GBP',
        'name_plural'=> __('British pounds sterling', 'fakturo' ),
    ),
    array(
        'symbol'=> 'GEL',
        'name'=> __('Georgian Lari', 'fakturo' ),
        'symbol_native'=> 'GEL',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'GEL',
        'name_plural'=> __('Georgian laris', 'fakturo' ),
    ),
    array(
        'symbol'=> 'GH₵',
        'name'=> __('Ghanaian Cedi', 'fakturo' ),
        'symbol_native'=> 'GH₵',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'GHS',
        'name_plural'=> __('Ghanaian cedis', 'fakturo' ),
    ),
    array(
        'symbol'=> 'FG',
        'name'=> __('Guinean Franc', 'fakturo' ),
        'symbol_native'=> 'FG',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'GNF',
        'name_plural'=> __('Guinean francs', 'fakturo' ),
    ),
    array(
        'symbol'=> 'GTQ',
        'name'=> __('Guatemalan Quetzal', 'fakturo' ),
        'symbol_native'=> 'Q',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'GTQ',
        'name_plural'=> __('Guatemalan quetzals', 'fakturo' ),
    ),
    array(
        'symbol'=> 'HK$',
        'name'=> __('Hong Kong Dollar', 'fakturo' ),
        'symbol_native'=> '$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'HKD',
        'name_plural'=> __('Hong Kong dollars', 'fakturo' ),
    ),
    array(
        'symbol'=> 'HNL',
        'name'=> __('Honduran Lempira', 'fakturo' ),
        'symbol_native'=> 'L',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'HNL',
        'name_plural'=> __('Honduran lempiras', 'fakturo' ),
    ),
    array(
        'symbol'=> 'kn',
        'name'=> __('Croatian Kuna', 'fakturo' ),
        'symbol_native'=> 'kn',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'HRK',
        'name_plural'=> __('Croatian kunas', 'fakturo' ),
    ),
    array(
        'symbol'=> 'Ft',
        'name'=> __('Hungarian Forint', 'fakturo' ),
        'symbol_native'=> 'Ft',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'HUF',
        'name_plural'=> __('Hungarian forints', 'fakturo' ),
    ),
    array(
        'symbol'=> 'Rp',
        'name'=> __('Indonesian Rupiah', 'fakturo' ),
        'symbol_native'=> 'Rp',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'IDR',
        'name_plural'=> __('Indonesian rupiahs', 'fakturo' ),
    ),
    array(
        'symbol'=> '₪',
        'name'=> __('Israeli New Sheqel', 'fakturo' ),
        'symbol_native'=> '₪',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'ILS',
        'name_plural'=> __('Israeli new sheqels', 'fakturo' ),
    ),
    array(
        'symbol'=> 'Rs',
        'name'=> __('Indian Rupee', 'fakturo' ),
        'symbol_native'=> 'টকা',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'INR',
        'name_plural'=> __('Indian rupees', 'fakturo' ),
    ),
    array(
        'symbol'=> 'IQD',
        'name'=> __('Iraqi Dinar', 'fakturo' ),
        'symbol_native'=> 'د.ع.‏',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'IQD',
        'name_plural'=> __('Iraqi dinars', 'fakturo' ),
    ),
    array(
        'symbol'=> 'IRR',
        'name'=> __('Iranian Rial', 'fakturo' ),
        'symbol_native'=> '﷼',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'IRR',
        'name_plural'=> __('Iranian rials', 'fakturo' ),
    ),
    array(
        'symbol'=> 'Ikr',
        'name'=> __('Icelandic Króna', 'fakturo' ),
        'symbol_native'=> 'kr',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'ISK',
        'name_plural'=> __('Icelandic krónur', 'fakturo' ),
    ),
    array(
        'symbol'=> 'J$',
        'name'=> __('Jamaican Dollar', 'fakturo' ),
        'symbol_native'=> '$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'JMD',
        'name_plural'=> __('Jamaican dollars', 'fakturo' ),
    ),
    array(
        'symbol'=> 'JD',
        'name'=> __('Jordanian Dinar', 'fakturo' ),
        'symbol_native'=> 'د.أ.‏',
        'decimal_digits'=> 3,
        'rounding'=> 0,
        'code'=> 'JOD',
        'name_plural'=> __('Jordanian dinars', 'fakturo' ),
    ),
    array(
        'symbol'=> '¥',
        'name'=> __('Japanese Yen', 'fakturo' ),
        'symbol_native'=> '￥',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'JPY',
        'name_plural'=> __('Japanese yen', 'fakturo' ),
    ),
    array(
        'symbol'=> 'Ksh',
        'name'=> __('Kenyan Shilling', 'fakturo' ),
        'symbol_native'=> 'Ksh',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'KES',
        'name_plural'=> __('Kenyan shillings', 'fakturo' ),
    ),
    array(
        'symbol'=> 'KHR',
        'name'=> __('Cambodian Riel', 'fakturo' ),
        'symbol_native'=> '៛',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'KHR',
        'name_plural'=> __('Cambodian riels', 'fakturo' ),
    ),
    array(
        'symbol'=> 'CF',
        'name'=> __('Comorian Franc', 'fakturo' ),
        'symbol_native'=> 'FC',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'KMF',
        'name_plural'=> __('Comorian francs', 'fakturo' ),
    ),
    array(
        'symbol'=> '₩',
        'name'=> __('South Korean Won', 'fakturo' ),
        'symbol_native'=> '₩',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'KRW',
        'name_plural'=> __('South Korean won', 'fakturo' ),
    ),
    array(
        'symbol'=> 'KD',
        'name'=> __('Kuwaiti Dinar', 'fakturo' ),
        'symbol_native'=> 'د.ك.‏',
        'decimal_digits'=> 3,
        'rounding'=> 0,
        'code'=> 'KWD',
        'name_plural'=> __('Kuwaiti dinars', 'fakturo' ),
    ),
    array(
        'symbol'=> 'KZT',
        'name'=> __('Kazakhstani Tenge', 'fakturo' ),
        'symbol_native'=> 'тңг.',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'KZT',
        'name_plural'=> __('Kazakhstani tenges', 'fakturo' ),
    ),
    array(
        'symbol'=> 'LB£',
        'name'=> __('Lebanese Pound', 'fakturo' ),
        'symbol_native'=> 'ل.ل.‏',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'LBP',
        'name_plural'=> __('Lebanese pounds', 'fakturo' ),
    ),
    array(
        'symbol'=> 'SLRs',
        'name'=> __('Sri Lankan Rupee', 'fakturo' ),
        'symbol_native'=> 'SL Re',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'LKR',
        'name_plural'=> __('Sri Lankan rupees', 'fakturo' ),
    ),
    array(
        'symbol'=> 'Lt',
        'name'=> __('Lithuanian Litas', 'fakturo' ),
        'symbol_native'=> 'Lt',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'LTL',
        'name_plural'=> __('Lithuanian litai', 'fakturo' ),
    ),
    array(
        'symbol'=> 'Ls',
        'name'=> __('Latvian Lats', 'fakturo' ),
        'symbol_native'=> 'Ls',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'LVL',
        'name_plural'=> __('Latvian lati', 'fakturo' ),
    ),
    array(
        'symbol'=> 'LD',
        'name'=> __('Libyan Dinar', 'fakturo' ),
        'symbol_native'=> 'د.ل.‏',
        'decimal_digits'=> 3,
        'rounding'=> 0,
        'code'=> 'LYD',
        'name_plural'=> __('Libyan dinars', 'fakturo' ),
    ),
    array(
        'symbol'=> 'MAD',
        'name'=> __('Moroccan Dirham', 'fakturo' ),
        'symbol_native'=> 'د.م.‏',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'MAD',
        'name_plural'=> __('Moroccan dirhams', 'fakturo' ),
    ),
    array(
        'symbol'=> 'MDL',
        'name'=> __('Moldovan Leu', 'fakturo' ),
        'symbol_native'=> 'MDL',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'MDL',
        'name_plural'=> __('Moldovan lei', 'fakturo' ),
    ),
    array(
        'symbol'=> 'MGA',
        'name'=> __('Malagasy Ariary', 'fakturo' ),
        'symbol_native'=> 'MGA',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'MGA',
        'name_plural'=> __('Malagasy Ariaries', 'fakturo' ),
    ),
    array(
        'symbol'=> 'MKD',
        'name'=> __('Macedonian Denar', 'fakturo' ),
        'symbol_native'=> 'MKD',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'MKD',
        'name_plural'=> __('Macedonian denari', 'fakturo' ),
    ),
    array(
        'symbol'=> 'MMK',
        'name'=> __('Myanma Kyat', 'fakturo' ),
        'symbol_native'=> 'K',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'MMK',
        'name_plural'=> __('Myanma kyats', 'fakturo' ),
    ),
    array(
        'symbol'=> 'MOP$',
        'name'=> __('Macanese Pataca', 'fakturo' ),
        'symbol_native'=> 'MOP$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'MOP',
        'name_plural'=> __('Macanese patacas', 'fakturo' ),
    ),
    array(
        'symbol'=> 'MURs',
        'name'=> __('Mauritian Rupee', 'fakturo' ),
        'symbol_native'=> 'MURs',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'MUR',
        'name_plural'=> __('Mauritian rupees', 'fakturo' ),
    ),
    array(
        'symbol'=> 'MX$',
        'name'=> __('Mexican Peso', 'fakturo' ),
        'symbol_native'=> '$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'MXN',
        'name_plural'=> __('Mexican pesos', 'fakturo' ),
    ),
    array(
        'symbol'=> 'RM',
        'name'=> __('Malaysian Ringgit', 'fakturo' ),
        'symbol_native'=> 'RM',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'MYR',
        'name_plural'=> __('Malaysian ringgits', 'fakturo' ),
    ),
    array(
        'symbol'=> 'MTn',
        'name'=> __('Mozambican Metical', 'fakturo' ),
        'symbol_native'=> 'MTn',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'MZN',
        'name_plural'=> __('Mozambican meticals', 'fakturo' ),
    ),
    array(
        'symbol'=> 'N$',
        'name'=> __('Namibian Dollar', 'fakturo' ),
        'symbol_native'=> 'N$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'NAD',
        'name_plural'=> __('Namibian dollars', 'fakturo' ),
    ),
    array(
        'symbol'=> '₦',
        'name'=> __('Nigerian Naira', 'fakturo' ),
        'symbol_native'=> '₦',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'NGN',
        'name_plural'=> __('Nigerian nairas', 'fakturo' ),
    ),
    array(
        'symbol'=> 'C$',
        'name'=> __('Nicaraguan Córdoba', 'fakturo' ),
        'symbol_native'=> 'C$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'NIO',
        'name_plural'=> __('Nicaraguan córdobas', 'fakturo' ),
    ),
    array(
        'symbol'=> 'Nkr',
        'name'=> __('Norwegian Krone', 'fakturo' ),
        'symbol_native'=> 'kr',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'NOK',
        'name_plural'=> __('Norwegian kroner', 'fakturo' ),
    ),
    array(
        'symbol'=> 'NPRs',
        'name'=> __('Nepalese Rupee', 'fakturo' ),
        'symbol_native'=> 'नेरू',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'NPR',
        'name_plural'=> __('Nepalese rupees', 'fakturo' ),
    ),
    array(
        'symbol'=> 'NZ$',
        'name'=> __('New Zealand Dollar', 'fakturo' ),
        'symbol_native'=> '$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'NZD',
        'name_plural'=> __('New Zealand dollars', 'fakturo' ),
    ),
    array(
        'symbol'=> 'OMR',
        'name'=> __('Omani Rial', 'fakturo' ),
        'symbol_native'=> 'ر.ع.‏',
        'decimal_digits'=> 3,
        'rounding'=> 0,
        'code'=> 'OMR',
        'name_plural'=> __('Omani rials', 'fakturo' ),
    ),
    array(
        'symbol'=> 'B/.',
        'name'=> __('Panamanian Balboa', 'fakturo' ),
        'symbol_native'=> 'B/.',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'PAB',
        'name_plural'=> __('Panamanian balboas', 'fakturo' ),
    ),
    array(
        'symbol'=> 'S/.',
        'name'=> __('Peruvian Nuevo Sol', 'fakturo' ),
        'symbol_native'=> 'S/.',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'PEN',
        'name_plural'=> __('Peruvian nuevos soles', 'fakturo' ),
    ),
    array(
        'symbol'=> '₱',
        'name'=> __('Philippine Peso', 'fakturo' ),
        'symbol_native'=> '₱',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'PHP',
        'name_plural'=> __('Philippine pesos', 'fakturo' ),
    ),
    array(
        'symbol'=> 'PKRs',
        'name'=> __('Pakistani Rupee', 'fakturo' ),
        'symbol_native'=> '₨',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'PKR',
        'name_plural'=> __('Pakistani rupees', 'fakturo' ),
    ),
    array(
        'symbol'=> 'zł',
        'name'=> __('Polish Zloty', 'fakturo' ),
        'symbol_native'=> 'zł',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'PLN',
        'name_plural'=> __('Polish zlotys', 'fakturo' ),
    ),
    array(
        'symbol'=> '₲',
        'name'=> __('Paraguayan Guarani', 'fakturo' ),
        'symbol_native'=> '₲',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'PYG',
        'name_plural'=> __('Paraguayan guaranis', 'fakturo' ),
    ),
    array(
        'symbol'=> 'QR',
        'name'=> __('Qatari Rial', 'fakturo' ),
        'symbol_native'=> 'ر.ق.‏',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'QAR',
        'name_plural'=> __('Qatari rials', 'fakturo' ),
    ),
    array(
        'symbol'=> 'RON',
        'name'=> __('Romanian Leu', 'fakturo' ),
        'symbol_native'=> 'RON',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'RON',
        'name_plural'=> __('Romanian lei', 'fakturo' ),
    ),
    array(
        'symbol'=> 'din.',
        'name'=> __('Serbian Dinar', 'fakturo' ),
        'symbol_native'=> 'дин.',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'RSD',
        'name_plural'=> __('Serbian dinars', 'fakturo' ),
    ),
    array(
        'symbol'=> 'RUB',
        'name'=> __('Russian Ruble', 'fakturo' ),
        'symbol_native'=> 'руб.',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'RUB',
        'name_plural'=> __('Russian rubles', 'fakturo' ),
    ),
    array(
        'symbol'=> 'RWF',
        'name'=> __('Rwandan Franc', 'fakturo' ),
        'symbol_native'=> 'FR',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'RWF',
        'name_plural'=> __('Rwandan francs', 'fakturo' ),
    ),
    array(
        'symbol'=> 'SR',
        'name'=> __('Saudi Riyal', 'fakturo' ),
        'symbol_native'=> 'ر.س.‏',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'SAR',
        'name_plural'=> __('Saudi riyals', 'fakturo' ),
    ),
    array(
        'symbol'=> 'SDG',
        'name'=> __('Sudanese Pound', 'fakturo' ),
        'symbol_native'=> 'SDG',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'SDG',
        'name_plural'=> __('Sudanese pounds', 'fakturo' ),
    ),
    array(
        'symbol'=> 'Skr',
        'name'=> __('Swedish Krona', 'fakturo' ),
        'symbol_native'=> 'kr',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'SEK',
        'name_plural'=> __('Swedish kronor', 'fakturo' ),
    ),
    array(
        'symbol'=> 'S$',
        'name'=> __('Singapore Dollar', 'fakturo' ),
        'symbol_native'=> '$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'SGD',
        'name_plural'=> __('Singapore dollars', 'fakturo' ),
    ),
    array(
        'symbol'=> 'Ssh',
        'name'=> __('Somali Shilling', 'fakturo' ),
        'symbol_native'=> 'Ssh',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'SOS',
        'name_plural'=> __('Somali shillings', 'fakturo' ),
    ),
    array(
        'symbol'=> 'SY£',
        'name'=> __('Syrian Pound', 'fakturo' ),
        'symbol_native'=> 'ل.س.‏',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'SYP',
        'name_plural'=> __('Syrian pounds', 'fakturo' ),
    ),
    array(
        'symbol'=> '฿',
        'name'=> __('Thai Baht', 'fakturo' ),
        'symbol_native'=> '฿',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'THB',
        'name_plural'=> __('Thai baht', 'fakturo' ),
    ),
    array(
        'symbol'=> 'DT',
        'name'=> __('Tunisian Dinar', 'fakturo' ),
        'symbol_native'=> 'د.ت.‏',
        'decimal_digits'=> 3,
        'rounding'=> 0,
        'code'=> 'TND',
        'name_plural'=> __('Tunisian dinars', 'fakturo' ),
    ),
    array(
        'symbol'=> 'T$',
        'name'=> __('Tongan Paʻanga', 'fakturo' ),
        'symbol_native'=> 'T$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'TOP',
        'name_plural'=> __('Tongan paʻanga', 'fakturo' ),
    ),
    array(
        'symbol'=> 'TL',
        'name'=> __('Turkish Lira', 'fakturo' ),
        'symbol_native'=> 'TL',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'TRY',
        'name_plural'=> __('Turkish Lira', 'fakturo' ),
    ),
    array(
        'symbol'=> 'TT$',
        'name'=> __('Trinidad and Tobago Dollar', 'fakturo' ),
        'symbol_native'=> '$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'TTD',
        'name_plural'=> __('Trinidad and Tobago dollars', 'fakturo' ),
    ),
    array(
        'symbol'=> 'NT$',
        'name'=> __('New Taiwan Dollar', 'fakturo' ),
        'symbol_native'=> 'NT$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'TWD',
        'name_plural'=> __('New Taiwan dollars', 'fakturo' ),
    ),
    array(
        'symbol'=> 'TSh',
        'name'=> __('Tanzanian Shilling', 'fakturo' ),
        'symbol_native'=> 'TSh',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'TZS',
        'name_plural'=> __('Tanzanian shillings', 'fakturo' ),
    ),
    array(
        'symbol'=> '₴',
        'name'=> __('Ukrainian Hryvnia', 'fakturo' ),
        'symbol_native'=> '₴',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'UAH',
        'name_plural'=> __('Ukrainian hryvnias', 'fakturo' ),
    ),
    array(
        'symbol'=> 'USh',
        'name'=> __('Ugandan Shilling', 'fakturo' ),
        'symbol_native'=> 'USh',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'UGX',
        'name_plural'=> __('Ugandan shillings', 'fakturo' ),
    ),
    array(
        'symbol'=> '$U',
        'name'=> __('Uruguayan Peso', 'fakturo' ),
        'symbol_native'=> '$',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'UYU',
        'name_plural'=> __('Uruguayan pesos', 'fakturo' ),
    ),
    array(
        'symbol'=> 'UZS',
        'name'=> __('Uzbekistan Som', 'fakturo' ),
        'symbol_native'=> 'UZS',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'UZS',
        'name_plural'=> __('Uzbekistan som', 'fakturo' ),
    ),
    array(
        'symbol'=> 'Bs.F.',
        'name'=> __('Venezuelan Bolívar', 'fakturo' ),
        'symbol_native'=> 'Bs.F.',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'VEF',
        'name_plural'=> __('Venezuelan bolívars', 'fakturo' ),
    ),
    array(
        'symbol'=> '₫',
        'name'=> __('Vietnamese Dong', 'fakturo' ),
        'symbol_native'=> '₫',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'VND',
        'name_plural'=> __('Vietnamese dong', 'fakturo' ),
    ),
    array(
        'symbol'=> 'FCFA',
        'name'=> __('CFA Franc BEAC', 'fakturo' ),
        'symbol_native'=> 'FCFA',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'XAF',
        'name_plural'=> __('CFA francs BEAC', 'fakturo' ),
    ),
    array(
        'symbol'=> 'CFA',
        'name'=> __('CFA Franc BCEAO', 'fakturo' ),
        'symbol_native'=> 'CFA',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'XOF',
        'name_plural'=> __('CFA francs BCEAO', 'fakturo' ),
    ),
    array(
        'symbol'=> 'YR',
        'name'=> __('Yemeni Rial', 'fakturo' ),
        'symbol_native'=> 'ر.ي.‏',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'YER',
        'name_plural'=> __('Yemeni rials', 'fakturo' ),
    ),
    array(
        'symbol'=> 'R',
        'name'=> __('South African Rand', 'fakturo' ),
        'symbol_native'=> 'R',
        'decimal_digits'=> 2,
        'rounding'=> 0,
        'code'=> 'ZAR',
        'name_plural'=> __('South African rand', 'fakturo' ),
    ),
    array(
        'symbol'=> 'ZK',
        'name'=> __('Zambian Kwacha', 'fakturo' ),
        'symbol_native'=> 'ZK',
        'decimal_digits'=> 0,
        'rounding'=> 0,
        'code'=> 'ZMK',
        'name_plural'=> __('Zambian kwachas', 'fakturo' ),
    )
);
?>